//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.AlbumTag = new HashSet<AlbumTag>();
            this.Cancion = new HashSet<Cancion>();
            this.LikeAlbum = new HashSet<LikeAlbum>();
        }
    
        public int AlbumId { get; set; }
        public string Titulo { get; set; }
        public string Imagen { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public string Formato { get; set; }
        public string Contenido { get; set; }
        public decimal Precio { get; set; }
        public decimal Oferta { get; set; }
        public string LinkCompra { get; set; }
        public string Promocion { get; set; }
        public int PerfilId { get; set; }
        public int SubGeneroId { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UrlAlbumPrecargado { get; set; }
        public Nullable<bool> UsarAlbumPrecargado { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual SubGenero SubGenero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumTag> AlbumTag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancion> Cancion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeAlbum> LikeAlbum { get; set; }
    }
}
