//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cancion()
        {
            this.LikeCancion = new HashSet<LikeCancion>();
        }
    
        public int CancionId { get; set; }
        public string Titulo { get; set; }
        public string Duracion { get; set; }
        public int NumeroTrack { get; set; }
        public string rutaArchivo { get; set; }
        public Nullable<bool> Tipo { get; set; }
        public int AlbumId { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string RutaArchivo { get; set; }
        public Nullable<int> Reproducciones { get; set; }
        public string Letra { get; set; }
    
        public virtual Album Album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeCancion> LikeCancion { get; set; }
    }
}
