//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeCancion
    {
        public int LikeCancionId { get; set; }
        public Nullable<int> PerfilId { get; set; }
        public Nullable<int> CancionId { get; set; }
    
        public virtual Cancion Cancion { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
