//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patrocinio
    {
        public int PatrocinioId { get; set; }
        public string Titulo { get; set; }
        public string Medio { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> EspacioId { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<bool> VentaTotal { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> TipoPatrocinio { get; set; }
        public string UrlEvento { get; set; }
        public Nullable<int> PerfilId { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string TipoArchivo { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual TipoPatrocinio TipoPatrocinio1 { get; set; }
    }
}
