//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilSociales
    {
        public int PerfilSocialId { get; set; }
        public string RedSocial { get; set; }
        public string Url { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> PerfilId { get; set; }
    
        public virtual Perfil Perfil { get; set; }
    }
}
