//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguridad_RolPerfil
    {
        public int RolPerfilId { get; set; }
        public int RolId { get; set; }
        public int PerfilId { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Seguridad_Rol Seguridad_Rol { get; set; }
    }
}
