//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguridad_Menu
    {
        public int MenuId { get; set; }
        public string Titulo { get; set; }
        public string UrlMenu { get; set; }
        public Nullable<int> PadreId { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<bool> EsPublico { get; set; }
        public string Icono { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Estatus { get; set; }
    }
}
