//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<AlbumTag> AlbumTag { get; set; }
        public virtual DbSet<Cancion> Cancion { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<EventoPerfil> EventoPerfil { get; set; }
        public virtual DbSet<EventoTag> EventoTag { get; set; }
        public virtual DbSet<EventoTipo> EventoTipo { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<LikeAlbum> LikeAlbum { get; set; }
        public virtual DbSet<LikeEvento> LikeEvento { get; set; }
        public virtual DbSet<LikePerfil> LikePerfil { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<PerfilTipo> PerfilTipo { get; set; }
        public virtual DbSet<SubGenero> SubGenero { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual int st_DelAlbum_(Nullable<int> albumId, Nullable<int> perfilId)
        {
            var albumIdParameter = albumId.HasValue ?
                new ObjectParameter("AlbumId", albumId) :
                new ObjectParameter("AlbumId", typeof(int));
    
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("st_DelAlbum_", albumIdParameter, perfilIdParameter);
        }
    
        public virtual int st_InsAlbum_(Nullable<int> albumId, string titulo, string imagen, Nullable<System.DateTime> fechaPublicacion, string formato, string contenido, Nullable<decimal> precio, Nullable<decimal> oferta, string linkCompra, string promocion, Nullable<int> perfilId, Nullable<int> subGeneroId, Nullable<bool> estatus, Nullable<System.DateTime> fechaRegistro)
        {
            var albumIdParameter = albumId.HasValue ?
                new ObjectParameter("AlbumId", albumId) :
                new ObjectParameter("AlbumId", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("Imagen", imagen) :
                new ObjectParameter("Imagen", typeof(string));
    
            var fechaPublicacionParameter = fechaPublicacion.HasValue ?
                new ObjectParameter("FechaPublicacion", fechaPublicacion) :
                new ObjectParameter("FechaPublicacion", typeof(System.DateTime));
    
            var formatoParameter = formato != null ?
                new ObjectParameter("Formato", formato) :
                new ObjectParameter("Formato", typeof(string));
    
            var contenidoParameter = contenido != null ?
                new ObjectParameter("Contenido", contenido) :
                new ObjectParameter("Contenido", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("Precio", precio) :
                new ObjectParameter("Precio", typeof(decimal));
    
            var ofertaParameter = oferta.HasValue ?
                new ObjectParameter("Oferta", oferta) :
                new ObjectParameter("Oferta", typeof(decimal));
    
            var linkCompraParameter = linkCompra != null ?
                new ObjectParameter("LinkCompra", linkCompra) :
                new ObjectParameter("LinkCompra", typeof(string));
    
            var promocionParameter = promocion != null ?
                new ObjectParameter("Promocion", promocion) :
                new ObjectParameter("Promocion", typeof(string));
    
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            var subGeneroIdParameter = subGeneroId.HasValue ?
                new ObjectParameter("SubGeneroId", subGeneroId) :
                new ObjectParameter("SubGeneroId", typeof(int));
    
            var estatusParameter = estatus.HasValue ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(bool));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("FechaRegistro", fechaRegistro) :
                new ObjectParameter("FechaRegistro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("st_InsAlbum_", albumIdParameter, tituloParameter, imagenParameter, fechaPublicacionParameter, formatoParameter, contenidoParameter, precioParameter, ofertaParameter, linkCompraParameter, promocionParameter, perfilIdParameter, subGeneroIdParameter, estatusParameter, fechaRegistroParameter);
        }
    
        public virtual ObjectResult<st_SelSubGeneroGetAll_Result> st_SelSubGeneroGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_SelSubGeneroGetAll_Result>("st_SelSubGeneroGetAll");
        }
    
        public virtual ObjectResult<st_SelAlbum__Result> st_SelAlbum_(Nullable<int> albumId, string titulo, Nullable<int> perfilId)
        {
            var albumIdParameter = albumId.HasValue ?
                new ObjectParameter("AlbumId", albumId) :
                new ObjectParameter("AlbumId", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<st_SelAlbum__Result>("st_SelAlbum_", albumIdParameter, tituloParameter, perfilIdParameter);
        }
    }
}
