//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perfil()
        {
            this.Albums = new HashSet<Album>();
            this.EventoPerfils = new HashSet<EventoPerfil>();
            this.LikeAlbums = new HashSet<LikeAlbum>();
            this.LikeEventoes = new HashSet<LikeEvento>();
            this.LikePerfils = new HashSet<LikePerfil>();
            this.LikePerfils1 = new HashSet<LikePerfil>();
        }
    
        public int PerfilId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<bool> Rol { get; set; }
        public int PerfilTipoId { get; set; }
        public string Nombre { get; set; }
        public string FotoPerfil { get; set; }
        public string AcercaDe { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public string UbicacionGM { get; set; }
        public string Horario { get; set; }
        public Nullable<System.DateTime> Fundacion { get; set; }
        public Nullable<int> CiudadId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album> Albums { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoPerfil> EventoPerfils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeAlbum> LikeAlbums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeEvento> LikeEventoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikePerfil> LikePerfils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikePerfil> LikePerfils1 { get; set; }
        public virtual PerfilTipo PerfilTipo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
