//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<AlbumTag> AlbumTags { get; set; }
        public virtual DbSet<Cancion> Cancions { get; set; }
        public virtual DbSet<Ciudad> Ciudads { get; set; }
        public virtual DbSet<Estado> Estadoes { get; set; }
        public virtual DbSet<Evento> Eventoes { get; set; }
        public virtual DbSet<EventoPerfil> EventoPerfils { get; set; }
        public virtual DbSet<EventoTag> EventoTags { get; set; }
        public virtual DbSet<EventoTipo> EventoTipoes { get; set; }
        public virtual DbSet<Genero> Generoes { get; set; }
        public virtual DbSet<LikeAlbum> LikeAlbums { get; set; }
        public virtual DbSet<LikeEvento> LikeEventoes { get; set; }
        public virtual DbSet<LikePerfil> LikePerfils { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<Perfil> Perfils { get; set; }
        public virtual DbSet<PerfilTipo> PerfilTipoes { get; set; }
        public virtual DbSet<SubGenero> SubGeneroes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
