//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukindieMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Album
    {
        public int AlbumId { get; set; }
        public string Titulo { get; set; }
        public string Imagen { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public string Formato { get; set; }
        public string Contenido { get; set; }
        public decimal Precio { get; set; }
        public decimal Oferta { get; set; }
        public string LinkCompra { get; set; }
        public string Promocion { get; set; }
        public int PerfilId { get; set; }
        public int SubGeneroId { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual SubGenero SubGenero { get; set; }

        public string FechaPublicacionTexto { get; set; }

        //public List<Models.Album> Get(int AlbumId, string Titulo, int PerfilId)
        //{
        //    try
        //    {
        //        List<Models.Album> litem = new List<Models.Album>();
        //        using (var db = new Models.YukindieEntities())
        //        {
        //            litem = db.st_SelAlbum_(AlbumId, Titulo, PerfilId)
        //        .Select(x => new Album
        //        {
        //            AlbumId = x.AlbumId,
        //            Titulo = x.Titulo,
        //            Imagen = x.Imagen,
        //            FechaPublicacionTexto = x.FechaPublicacion.ToString("dd/mm/yyyy"),
        //            Formato = x.Formato,
        //            Contenido = x.Contenido,
        //            Precio = x.Precio,
        //            Oferta = x.Oferta,
        //            LinkCompra = x.LinkCompra,
        //            Promocion = x.Promocion,
        //            PerfilId = x.PerfilId,
        //            Estatus = x.Estatus,
        //            SubGenero = new SubGenero
        //            {
        //                SubGeneroId = x.SubGeneroId,
        //                Descripcion = x.SubGenero
        //            }
        //        }).ToList();

        //        }

        //        return litem;
        //    }
        //    catch (Exception)
        //    {

        //        throw;
        //    }
        //}

        //public void guardar(Models.Album item)
        //{
        //    try
        //    {
        //        using (var db = new Models.YukindieEntities())
        //        {
        //            db.st_InsAlbum_(item.AlbumId, item.Titulo,item.Imagen,item.FechaPublicacion,item.Formato,item.Contenido,item.Precio,item.Oferta,item.LinkCompra,item.Promocion,item.PerfilId,item.SubGenero.SubGeneroId,item.Estatus,item.FechaRegistro);
        //        }

        //    }
        //    catch (Exception)
        //    {

        //        throw;
        //    }
        //}

        //public void eliminar(Models.Album item)
        //{
        //    try
        //    {
        //        using (var db = new Models.YukindieEntities())
        //        {
        //            db.st_DelAlbum_(item.AlbumId, item.PerfilId);
        //        }

        //    }
        //    catch (Exception)
        //    {

        //        throw;
        //    }
        //}

    }
}
