//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukindieMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SubGenero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubGenero()
        {
            this.Album = new HashSet<Album>();
        }
    
        public int SubGeneroId { get; set; }
        public string Descripcion { get; set; }
        public int GeneroId { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album> Album { get; set; }

        public List<Models.SubGenero> Get()
        {
            try
            {
                List<Models.SubGenero> litem = new List<Models.SubGenero>();
                using (var db = new Models.YukindieEntities())
                {
                    litem = db.st_SelSubGeneroGetAll()
                .Select(x => new SubGenero
                {
                    SubGeneroId = x.SubGeneroId,
                    Descripcion = x.Descripcion
                }).ToList();

                }

                return litem;
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}
